swagger: '2.0'
info:
  title: Argent Bank API
  description: API pour la gestion des transactions dans Argent Bank
  version: '1.0.0'

paths:
  # Route pour récupérer toutes les transactions d'un utilisateur pour le mois en cours
  /api/v1/transactions:
    get:
      summary: "Récupérer toutes les transactions pour un utilisateur pour le mois en cours"
      description: "Retourne toutes les transactions pour l'utilisateur, groupées par compte."
      parameters:
        - name: "userId"
          in: "query"
          description: "ID de l'utilisateur"
          required: true
          type: "string"
      responses:
        200:
          description: "Transactions récupérées avec succès"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    transactionId:
                      type: "string"
                    amount:
                      type: "number"
                    type:
                      type: "string"
                    date:
                      type: "string"
                    accountId:
                      type: "string"
        400:
          description: "Requête invalide"
        401:
          description: "Non autorisé, token manquant"
        404:
          description: "Aucune transaction trouvée"
        500:
          description: "Erreur interne du serveur"

  # Route pour récupérer les détails d'une transaction spécifique
  /api/v1/transactions/{transactionId}:
    get:
      summary: "Récupérer les détails d'une transaction"
      description: "Retourne les détails d'une transaction spécifique."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction"
          required: true
          type: "string"
      responses:
        200:
          description: "Transaction trouvée avec succès"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  transactionId:
                    type: "string"
                  amount:
                    type: "number"
                  type:
                    type: "string"
                  date:
                    type: "string"
                  accountId:
                    type: "string"
        404:
          description: "Transaction non trouvée"
        500:
          description: "Erreur interne du serveur"

  # Route pour mettre à jour une transaction
  /api/v1/transactions/{transactionId}:
    put:
      summary: "Mettre à jour une transaction"
      description: "Permet de modifier des informations sur une transaction, comme le montant ou la description."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction"
          required: true
          type: "string"
        - name: "amount"
          in: "body"
          description: "Le montant de la transaction"
          required: true
          schema:
            type: "number"
        - name: "type"
          in: "body"
          description: "Le type de la transaction (crédit ou débit)"
          required: false
          schema:
            type: "string"
        - name: "description"
          in: "body"
          description: "La description de la transaction"
          required: false
          schema:
            type: "string"
      responses:
        200:
          description: "Transaction mise à jour avec succès"
        400:
          description: "Requête invalide, données manquantes ou incorrectes"
        404:
          description: "Transaction non trouvée"
        500:
          description: "Erreur interne du serveur"

  # Route pour supprimer une transaction (pas nécessaire ici)
  # Cette route est incluse à titre d'exemple. Dans votre cas, elle ne sera pas utilisée.
  /api/v1/transactions/{transactionId}:
    delete:
      summary: "Supprimer une transaction"
      description: "Supprime une transaction spécifique. Non utilisée dans ce projet."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction à supprimer"
          required: true
          type: "string"
      responses:
        200:
          description: "Transaction supprimée avec succès"
        404:
          description: "Transaction non trouvée"
        500:
          description: "Erreur interne du serveur"
